### ISSUE TITLE
Prof finds student for capstone without passing through MLL site (common scenario)

### ISSUE THREAD

**Issue by fuhrmanator** [MaisonLogicielLibre/Website#811] opened 2016-01-15 21:58 UTC
I have started a capstone with a student for [this mission](https://maisonlogiciellibre.org/missions/view/34), but the student never registered with MLL. He was assigned to me by the department chair. This is the normal workflow before MLL. 

The scenario is that students are assigned to profs by the department chair, but the students need to find projects. Sometimes I give a summary of projects that such students could work on (some of the projects are in MLL). Once a student starts her capstone, I would like to declare in the MLL site that the student is now assigned to the mission.

I could ask the student to create an account and go through all the steps, but it seems clunky. Is there a better way? 

I have also a master's student for [this mission](https://maisonlogiciellibre.org/missions/view/51) who officially started this semester.

**Comment by fxleblanc** [comment] 2016-01-16 16:25
@fuhrmanator, @RignonNoel and I found a solution to this problem. I named it IPE which stands for Industrie-Professeur-Étudiant. The new IPE relationship and workflow is outlined in #791 and also in the pull request #806. The two uml diagrams in the pull request outline both the new workflow and what the new model will change in the database. Tell me what you think about it in the issue and if something is missing in the uml, I encourage you to comment on the pull request.

I'll close this issue for now since all the documentation about you are asking is in the issue and in the pull request.

**Closed by fxleblanc** 2016-01-16 16:25 UTC

**Comment by fuhrmanator** [comment] 2016-01-18 18:17
Here's a view of the UML:
![diagram in UML](http://www.plantuml.com/plantuml/proxy?fmt=svg&src=https://raw.githubusercontent.com/fxleblanc/Website/3b5cd027d6fd1c224ef93a1d9e9fac968fce8eed/doc/IPE-relationship-activity.uml)

Here are my comments:

 - The UML syntax is confusing. The true/false steps should be after a question. You'd get a bad mark if this was in LOG210 :-)
 - At the step "Industrie choisit le type PFE" this is a high-risk step, meaning they're not experts to know what a PFE is. Only a professor will know, and these conditions will vary a lot depending on the university and even the professor. 
 - I don't follow well the process where the user, student and professor somehow get together on the project.
 - I've been doing capstone and master's projects for almost 15 years, and there's no pre-determined way this happens. Sometimes I have an idea that I give the student, sometimes the student suggests an idea (but it's rare that student ideas are sufficient on the first attempt), sometimes it's a combination of brainstorming in my office. The point is, it's going to be hard to model this (it's complex).

This solution is too complex and unclear (to me), even with the UML model. 

Why does industry have to be part of the pairing? It's my experience that a relatively small number of capstone projects are done with an industrial partner. 

Students can propose missions they'd like to do for a capstone. Professors can, too. 

ML2's raison-d'être is about getting as many students to work on open source projects, so that companies (like Google) can see how they code and work in teams. Industry can be there, but it's not essential (unless I'm wrong on the direction of ML2).

**Comment by fuhrmanator** [comment] 2016-01-18 18:21
My initial comment was also because I want to show that there are projects that are ongoing with ML2, even though I didn't match my students using your site. I think you still want to show that, right? Can you please read the first comment to better understand? Thanks!

**Comment by fxleblanc** [comment] 2016-01-18 18:30
You're right, the Capstone use case is very complex and the diagram pretty unclear. The use case I tried to present here only takes into account when an organization presents a mission. What you suggested in #654 would solve that issue because it's the professor who would decide which mission is fit to be a Capstone.

**Comment by fxleblanc** [comment] 2016-01-18 18:37
To answer your third point, it all starts with the organization. It submits a mission with the type Capstone, knowing that it targets a teacher/student pair. Then, the teacher or the student notice the project and accept it. The action of accepting the project only means that the student or professor will notify his interest to the other party(student or professor). The other party then decides if it's good or not. When the pair is created, the organization is then notified and the Capstone is confirmed.

**Comment by fuhrmanator** [comment] 2016-06-04 12:29
This point is closed, but I still don't know how I (as a prof who created missions) can show that I finally found a student working on a mission. I realize capstones are hard to model, and I don't think it's worth coding all the complexities. But it's very important that ML2 track which students are actually working on projects and that profs have a documented way to get that info back into ML2. @appliedrd
